Kutuphane/Controllers/HomeController.cs
using System.Diagnostics;
using Kutuphane.Data;
using Kutuphane.Models;
using Microsoft.AspNetCore.Mvc;

namespace Kutuphane.Controllers
{
    public class HomeController : Controller
    {
        //private readonly KutuphaneContext _context;
        //public HomeController(KutuphaneContext context)
        //{
        //    _context = context;
        //}

        private readonly KutuphaneContext _context;

        public HomeController(KutuphaneContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

     
       
    }
}

Kutuphane/Controllers/KitapController.cs
using System.Reflection;
using Kutuphane.Data;
using Kutuphane.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Kutuphane.Controllers
{
	public class KitapController : Controller
	{
		private readonly KutuphaneContext _context;

		public KitapController(KutuphaneContext context)
		{
			_context = context;
		}
		public IActionResult Index()
		{
			//_context.Kitaplar.Select(k=> new
			//{
			//    k.Id,
			//    k.Ad,
			//    k.Yazarlar,
			//    k.YayinEvleri,

			//})


			return View(_context.Kitaplar.Include(k => k.YayinEvleri).Include(k => k.Yazarlar).ToList());
		}

		public IActionResult Add()
		{
			
			ViewData["Yazarlar"] = _context.Yazarlar.ToList();
			ViewData["YayinEvleri"] = _context.YayinEvleri.ToList();
			return View();
		}

		[HttpPost]
		public IActionResult Add(Kitap kitap, List<string> yazarlar, List<string>yayinEvleri)
		{
			foreach (string s in yazarlar)
				kitap.Yazarlar.Add(_context.Yazarlar.Find(int.Parse(s)));
			
			foreach (string s in yayinEvleri)
				kitap.YayinEvleri.Add(_context.YayinEvleri.Find(int.Parse(s)));
			
			_context.Kitaplar.Add(kitap);
			_context.SaveChanges();
			return RedirectToAction("Index");

		}

		public IActionResult Update(int id)
		{
			ViewData["Yazarlar"] = _context.Yazarlar.ToList();
			ViewData["YayinEvleri"] = _context.YayinEvleri.ToList();

			return View(_context.Kitaplar.Include(k=>k.Yazarlar).Include(k=>k.YayinEvleri).FirstOrDefault(k=>k.Id==id));
		}

		public IActionResult Update(Kitap kitap, List<int> yazarlar, List<int> yayinEvleri)
		{
			Kitap asil = _context.Kitaplar.Include(k=>k.YayinEvleri).Include(k=>k.Yazarlar).FirstOrDefault(k=>k.Id==kitap.Id);
			asil.Ad=kitap.Ad;
			asil.ISBN=kitap.ISBN;

			List<Yazar>YazarListesi= new List<Yazar>();
			List<YayinEvi>YayinEvleriListesi= new List<YayinEvi>();

			foreach (int s in yazarlar)
				YazarListesi.Add(_context.Yazarlar.Find(s));

			foreach (int s in yayinEvleri)
				YayinEvleriListesi.Add(_context.YayinEvleri.Find(s));

			asil.Yazarlar = YazarListesi;
			asil.YayinEvleri= YayinEvleriListesi;

			_context.Kitaplar.Update(asil);
			_context.SaveChanges();
			return RedirectToAction("Index");

		}

	}
}

Kutuphane/Controllers/YayinEviController.cs
using System.Linq;
using Kutuphane.Data;
using Kutuphane.Models;
using Microsoft.AspNetCore.Mvc;

namespace Kutuphane.Controllers
{
    public class YayinEviController: Controller
    {
        private readonly KutuphaneContext _context;
        public YayinEviController(KutuphaneContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {

            return View(_context.YayinEvleri.ToList());
        }

        //public IActionResult Add()
        //{
        //    return View();
        //}
        //[HttpPost]

        //public IActionResult Add(YayinEvi yayinEvi) 
        //{
        //    _context.YayinEvleri.Add(yayinEvi);
        //    _context.SaveChanges();
        //    return RedirectToAction("Index");
        //}

        public IActionResult Delete(int id)
        {
            _context.YayinEvleri.Remove(_context.YayinEvleri.Find(id));
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

		public IActionResult UpSert(int? id)
		{
			if (id == 0)
			{
				return View();
			}
            else
            {
				return View(_context.YayinEvleri.Find(id));
			}
			
		}
        [HttpPost]
		public IActionResult UpSert(YayinEvi yayinEvi)
		{
            if (yayinEvi != null)
            {
				if (yayinEvi.Id == 0)
				{
					_context.YayinEvleri.Add(yayinEvi);

				}
				else
				{
					_context.YayinEvleri.Update(yayinEvi);

				}
				_context.SaveChanges();
			}
		
			return RedirectToAction("Index");
		}


		//public IActionResult Update (int id)
  //      {
  //          return View(_context.YayinEvleri.Find(id));
  //      }
  //      [HttpPost]

  //      public IActionResult Update(YayinEvi yayinEvi)
  //      {
  //          _context.YayinEvleri.Update(yayinEvi);
  //          _context.SaveChanges();
  //          return RedirectToAction("Index");
  //      }
    }
}

Kutuphane/Controllers/YazarController.cs
using Kutuphane.Data;
using Kutuphane.Models;
using Microsoft.AspNetCore.Mvc;

namespace Kutuphane.Controllers
{
    public class YazarController : Controller
    {
        //Dependency Injection
        private readonly KutuphaneContext _context;

        public YazarController(KutuphaneContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            //List<Yazar> yazarlar=_context.Yazarlar.ToList<Yazar>();

            //2.yol
            return View(_context.Yazarlar.ToList<Yazar>());
        }

        //public IActionResult Add()
        //{
        //    return View();
        //}
        //[HttpPost]
        //public IActionResult Add(Yazar yazar)
        //{
        //    _context.Yazarlar.Add(yazar);
        //    _context.SaveChanges();
        //    return RedirectToAction("Index");
        //}

        public IActionResult Delete(int id)
        {
            //1.yol
            //Yazar yazar= _context.Yazarlar.Find(id);
            //_context.Yazarlar.Remove(yazar);

            //Bu yol uzun kullanma
            //Yazar yazar = _context.Yazarlar.Where(y=>y.Id == id).First(); //Bir serinin-dizinin ilk elementi isteme

            //
            //Yazar yazar1 = _context.Yazarlar.FirstOrDefault(y => y.Id == id); //O kritere uyan birden fazla şey olsa bile ilk yakaladıgını getiriyor sana 

            //Kısa yol //En iyi yol
            _context.Yazarlar.Remove(_context.Yazarlar.Find(id));

            _context.SaveChanges();

            return RedirectToAction("Index");
        }

        //public IActionResult Update(int id)
        //{
        //    return View(_context.Yazarlar.Find(id));
        //}

        public IActionResult UpSert(int? id)
        {
            if (id!=null)
            {
                return View(_context.Yazarlar.Find(id));
            }
            else
            {
				return View();
			}
          
        }
        [HttpPost]
        public IActionResult UpSert(Yazar yazar)
        {
            if (yazar.Id == 0)
            {
                _context.Yazarlar.Add(yazar);
                _context.SaveChanges();
            }
            else
            {
                _context.Yazarlar.Update(yazar);
                _context.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        //[HttpPost]
        //public IActionResult Update(Yazar yazar)
        //{
        //    _context.Yazarlar.Update(yazar);
        //    _context.SaveChanges();
        //    return RedirectToAction("Index");
        //}
        
    }
}

Kutuphane/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Kutuphane/Views/Kitap/Add.cshtml
@model Kitap

@{
	var yazarlar = ViewData["Yazarlar"] as List<Yazar>;
	var yayinEvleri = ViewData["YayinEvleri"] as List<YayinEvi>;
}
<form method="post">


	<input asp-for="Ad" placeholder="Kitap adi:" class="form-control" />
	<input asp-for="ISBN" placeholder="Kitap ISBN:" class="form-control" />

	<select asp-for="Yazarlar" asp-items="@(new SelectList(yazarlar,"Id","Ad"))" multiple="multiple" class="form-control"></select>
		
	<select asp-for="YayinEvleri" asp-items="@(new SelectList(yayinEvleri,"Id","Ad"))" multiple="multiple" class="form-control"></select>
			
	<button class="btn btn-primary" type="submit">Kaydet</button>

</form>

Kutuphane/Views/Kitap/Index.cshtml
@model List<Kitap>
<a asp-action="Add" asp-controller="Kitap" class="btn btn-primary" >Ekle</a>

	<table class="table table-striped">
		<thead>
			<tr>
			<td>Ad</td>
			<td>ISBN</td>
			<td>Yazarlar</td>
			<td>YayınEvleri</td>
			<td>İşlemler</td>

			</tr>

		</thead>
		<tbody>
		@foreach(Kitap kitap in Model)
		{
			<tr>
				<td>@kitap.Ad</td>
				<td>@kitap.ISBN</td>
				<td>
					@foreach(Yazar yazar in kitap.Yazarlar)
					{
						@yazar.Ad <br />
					}
				</td>
				<td>
					@foreach (YayinEvi yayinEvi in kitap.YayinEvleri)
					{
						@yayinEvi.Ad <br />
					}
					
				</td>
				<td><a asp-action="Delete" asp-controller="Kitap" asp-all-route-id="@kitap.Id" class="btn btn-danger">Sil</a> </td>

			</tr>
		}
		</tbody>











	</table> 

Kutuphane/Views/Kitap/Update.cshtml
@model Kitap

@{
	var yazarlar = ViewData["Yazarlar"] as List<Yazar>;
	var yayinEvleri = ViewData["YayinEvleri"] as List<YayinEvi>;
}
<form method="post">


	<input asp-for="Ad" value="@Model.Ad" placeholder="Kitap adi:" class="form-control" />
	<input asp-for="ISBN" value="@Model.ISBN" placeholder="Kitap ISBN:" class="form-control" />

	<select asp-for="Yazarlar" asp-items="@(new SelectList(yazarlar,"Id","Ad",Model.Yazarlar))" multiple="multiple" class="form-control"></select>

	<select asp-for="YayinEvleri" asp-items="@(new SelectList(yayinEvleri,"Id","Ad"))" multiple="multiple" class="form-control"></select>

	<button class="btn btn-primary" type="submit">Kaydet</button>

</form>

Kutuphane/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Kutuphane</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Kutuphane.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Kutuphane</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Yazar" asp-action="Index">Yazarlar</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="YayinEvi" asp-action="Index">Yayinevleri</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Kitap" asp-action="Index">Kitaplar</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Kutuphane - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Kutuphane/Views/YayinEvi/Index.cshtml
@model List<YayinEvi>

<a asp-controller="YayinEvi" asp-action="UpSert" class="btn btn-primary">Ekle</a>

<table id="tblYayinEvi" class="table table-striped">
    <thead>
        <tr>
            <th>Yayinevi adı</th>
            <th>Yayinevi adresi</th>
            <th>Yayinevi tel</th>
            <th>işlemler</th>
        </tr>
    </thead>
    <tbody>

        @foreach (YayinEvi item in Model)
        {
            <tr>
                <td>@item.Ad</td>
                <td>@item.Adres</td>
                <td>@item.Tel</td>
                <td>
                    <a onclick="return confirm (Silmek istediğinizden emin misiniz?)"
                     asp-action="Delete" asp-controller="YayinEvi" asp-route-id="@item.Id" class="btn btn-danger">Sil</a> |
                    <a asp-action="UpSert" asp-controller="YayinEvi" asp-route-id="@item.Id" class="btn btn-success">Düzenle</a>
                </td>
            </tr>
        }


    </tbody>

Kutuphane/Views/YayinEvi/Update.cshtml
@model YayinEvi

<form method="post" action="">

	<input asp-for="Ad" class="form-control" placeholder="Yayinevi ADI :" value="@Model.Ad" /> <br />
	<input asp-for="Adres" class="form-control" placeholder="Yayinevi Adresi :" value="@Model.Adres" /> <br />
	<input asp-for="Tel" class="form-control" placeholder="Yayinevi tel" :" value="@Model.Tel" /> <br />

	<button class="btn btn-success" type="submit">Güncelle</button>


</form>

Kutuphane/Views/YayinEvi/Upsert.cshtml
@model YayinEvi

@if (Model == null)
{
	<form method="post" action="">

		<input asp-for="Ad" class="form-control" placeholder="Yayınevi ADI :" /> <br />
		<input asp-for="Adres" class="form-control" placeholder="Yayinevi Adresi :" /> <br />
		<input asp-for="Tel" class="form-control" placeholder="Yayinevi tel :" /> <br />

		<button class="btn btn-primary" type="submit">Kaydet</button>


	</form>



}else{ 



<form method="post" action="">

	<input asp-for="Ad" class="form-control" placeholder="Yayinevi ADI :" value="@Model.Ad" /> <br />
	<input asp-for="Adres" class="form-control" placeholder="Yayinevi Adresi :" value="@Model.Adres" /> <br />
	<input asp-for="Tel" class="form-control" placeholder="Yayinevi tel" :" value="@Model.Tel" /> <br />

	<button class="btn btn-success" type="submit">Güncelle</button>


</form>
}

Kutuphane/Views/Yazar/Index.cshtml
@model List<Yazar> 

<a asp-controller="Yazar" asp-action="Upsert" class="btn btn-primary">Ekle</a>

<table id="tblYazarlar" class="table table-striped"> 
    <thead>
        <tr>
            <th>Yazar adı</th>
            <th>Yazar Özgeçmiş</th>
            <th>İşlemler</th>
        </tr>
    </thead>
    <tbody>


        @foreach(Yazar item in Model)
        {
            <tr>
            <td>@item.Ad</td>
            <td>@item.Ozgecmis</td>
        <td> <a asp-action="Delete" asp-controller="Yazar" asp-route-id="@item.Id" class="btn btn-danger">Sil</a> | 
            <a asp-action="UpSert" asp-controller="Yazar" asp-route-id="@item.Id" class="btn btn-success">Düzenle</a></td>
            </tr>
        }
        

    </tbody>

</table>

Kutuphane/Views/Yazar/UpSert.cshtml
@model Yazar

@if (Model != null)
{

	<form method="post" action="">

		<input asp-for="Ad" class="form-control" placeholder="YAZARIN ADI :" value="@Model.Ad" /> <br />
		<input asp-for="Ozgecmis" class="form-control" placeholder="YAZARIN Özgeçmişi :" value="@Model.Ozgecmis" /> <br />

		<button class="btn btn-success" type="submit">Güncelle</button>


	</form>
}
else
{

	<form method="post" action="">

		<input asp-for="Ad" class="form-control" placeholder="YAZARIN ADI :" /> <br />
		<input asp-for="Ozgecmis" class="form-control" placeholder="YAZARIN Özgeçmişi :" /> <br />

		<button class="btn btn-primary" type="submit">Ekle/button>


	</form>
}